// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pdfcomposestream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PdfComposeClient is the client API for PdfCompose service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PdfComposeClient interface {
	PostSend(ctx context.Context, opts ...grpc.CallOption) (PdfCompose_PostSendClient, error)
}

type pdfComposeClient struct {
	cc grpc.ClientConnInterface
}

func NewPdfComposeClient(cc grpc.ClientConnInterface) PdfComposeClient {
	return &pdfComposeClient{cc}
}

func (c *pdfComposeClient) PostSend(ctx context.Context, opts ...grpc.CallOption) (PdfCompose_PostSendClient, error) {
	stream, err := c.cc.NewStream(ctx, &PdfCompose_ServiceDesc.Streams[0], "/pdfcompose.PdfCompose/PostSend", opts...)
	if err != nil {
		return nil, err
	}
	x := &pdfComposePostSendClient{stream}
	return x, nil
}

type PdfCompose_PostSendClient interface {
	Send(*Upfile) error
	Recv() (*Pdf, error)
	grpc.ClientStream
}

type pdfComposePostSendClient struct {
	grpc.ClientStream
}

func (x *pdfComposePostSendClient) Send(m *Upfile) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pdfComposePostSendClient) Recv() (*Pdf, error) {
	m := new(Pdf)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PdfComposeServer is the server API for PdfCompose service.
// All implementations must embed UnimplementedPdfComposeServer
// for forward compatibility
type PdfComposeServer interface {
	PostSend(PdfCompose_PostSendServer) error
	mustEmbedUnimplementedPdfComposeServer()
}

// UnimplementedPdfComposeServer must be embedded to have forward compatible implementations.
type UnimplementedPdfComposeServer struct {
}

func (UnimplementedPdfComposeServer) PostSend(PdfCompose_PostSendServer) error {
	return status.Errorf(codes.Unimplemented, "method PostSend not implemented")
}
func (UnimplementedPdfComposeServer) mustEmbedUnimplementedPdfComposeServer() {}

// UnsafePdfComposeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PdfComposeServer will
// result in compilation errors.
type UnsafePdfComposeServer interface {
	mustEmbedUnimplementedPdfComposeServer()
}

func RegisterPdfComposeServer(s grpc.ServiceRegistrar, srv PdfComposeServer) {
	s.RegisterService(&PdfCompose_ServiceDesc, srv)
}

func _PdfCompose_PostSend_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PdfComposeServer).PostSend(&pdfComposePostSendServer{stream})
}

type PdfCompose_PostSendServer interface {
	Send(*Pdf) error
	Recv() (*Upfile, error)
	grpc.ServerStream
}

type pdfComposePostSendServer struct {
	grpc.ServerStream
}

func (x *pdfComposePostSendServer) Send(m *Pdf) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pdfComposePostSendServer) Recv() (*Upfile, error) {
	m := new(Upfile)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PdfCompose_ServiceDesc is the grpc.ServiceDesc for PdfCompose service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PdfCompose_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pdfcompose.PdfCompose",
	HandlerType: (*PdfComposeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PostSend",
			Handler:       _PdfCompose_PostSend_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/PdfComposeService.proto",
}
